### ISSUE TITLE
Vinicius Santana - Mobile - Belo Horizonte/MG

### ISSUE THREAD

**Issue by vsanrocha** [training-center/primeiro-trampo#10]
# Vinicius Santana
## Foco 
Mobile / Front-End
## Cidade/Estado
Belo Horizonte/MG
## LinkedIn
[/viniciussrocha](https://www.linkedin.com/in/viniciussrocha/)
## Portfólio
[/vsanrocha](https://github.com/vsanrocha)
## Skills

- Java
- Git
- Inglês(Intermediário)

## Contato
vsanrocha@gmail.com
[Facebook](https://www.facebook.com/vsrocha89)

**Comment by vsanrocha** [comment]
Consegui o meu primeiro emprego.. vlw pessoas pela a ajuda!

**Comment by woliveiras** [comment]
Aeeee! Parabéns, mano!

**Comment by vsanrocha** [comment]
Vlwww... Eu que tenho que agradecer.. o TC me ajudou de mais!!
