### ISSUE TITLE
Mariana Brito - Fontend - Curitiba/PR

### ISSUE THREAD

**Issue by erenbrito** [training-center/primeiro-trampo#3]
# Mariana Brito

## Foco
Frontend

## Cidade:
Curitiba/PR

## LinkedIn:
[/marianabritosouza](www.linkedin.com/in/marianabritosouza)

## Portfólio:
[/BritoMari](https://codepen.io/BritoMari/)

## skills:
 - HTML5
 - CSS3
 - Javascript(Básico)
 - Git
 - PHP(Iniciando os estudos)
 - Inglês(Intermediário)
 
## Contato:
mariana.bsouza@hotmail.com
https://twitter.com/briitomari
https://about.me/marianabrito
https://crazywoman.top

**Comment by Diego-Brocanelli** [comment]
Olá, @BritoMari.

Dá uma olhada para ver se interessa, estão procurando front-end jr.

[[Curitiba] Front-End Developer na Neeuron](https://github.com/frontendbr/vagas/issues/580)

**Comment by erenbrito** [comment]
Irei enviar meu currículo, obrigado @Diego-Brocanelli

**Comment by Diego-Brocanelli** [comment]
Imagina, boa sorte e sucesso!
